name: salesiq_mobilisten
description: Mobilisten enables you to give your users the best in-app live chat experience. Mobilisten provides drop-in in-app chat and knowledge base.
version: 1.0.2
repository: https://github.com/zoho/salesiq-mobilisten-flutter
homepage: https://mobilisten.io/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zohosalesiq.plugin
        pluginClass: MobilistenPlugin
      ios:
        pluginClass: MobilistenPlugin
